### ISSUE TITLE
Negative dates in milliseconds are not correctly transformed to dates in MongoSink

### ISSUE THREAD

**Issue by jgduartestratio** [Stratio/Ingestion#224]
There is a condition in the code that makes any negative value to be dealt as an ISO date.
_StringUtils.isNumeric(stringValue)_ of a negative number returns false.

**Comment by epeinado** [comment]
Hi jgduartestratio,

We have been investigating about this bug and it looks like Apache knows it is a bug but they can't correct it to keep backwards compatibility (you can read it [here](https://issues.apache.org/jira/browse/LANG-428), is the same problem with an empty string). I have been speaking with mpenate and we have merged your PR.

Thanks for your collaboration!!
